"""Missions-database forum: every mission from einsaetze.json as a post.

One forum post per mission, tagged and fully rendered in English. The bot
owns the forum: it creates the tag set itself, turns ``require_tag`` on,
posts new missions, and edits an existing post's starter message in place
when the mission's data changes (no bump, no duplicate). Missions that
disappear from the JSON keep their post (threads auto-archive but stay
searchable).

Duplicate prevention is the ``missions_forum_posts`` table (mission_key →
thread_id + content hash). Should the database ever be lost, posts are
re-adopted from the thread titles (``… · #<key>``) instead of reposted.

Rate limits: discord.py already retries HTTP 429s; on top of that every
create/edit is followed by a small pause (plus a longer one per batch) and
each run posts at most ``max_posts_per_run`` — the initial ~450-mission
backfill spreads over a few runs.
"""

from __future__ import annotations

import asyncio
import datetime as dt
import logging
import re

import discord

from ..config import Config
from ..db.database import Database
from ..db.repos import MissionsForumRepo, StateRepo
from ..mc import missions_catalog as catalog
from ..mc.client import MissionChiefClient

log = logging.getLogger(__name__)

STATE_LAST_SYNC = "missions_forum:last_sync"
# Set once a sync has covered the whole catalog without hitting the post
# cap. Announcements only fire after that: the multi-run initial backfill
# must never ping the announcement channel, not even its later runs.
STATE_BACKFILL_DONE = "missions_forum:backfill_done"

# Thread titles end in " · #<key>" — the recovery marker that lets the bot
# re-adopt its own posts after a database loss.
_TITLE_KEY_RE = re.compile(r"·\s*#(\S+)\s*$")

_DISCIPLINE_COLOURS = {
    "Fire": 0xE74C3C,
    "EMS": 0xE67E22,
    "Police": 0x3498DB,
    "Federal": 0x2C3E50,
    "Water": 0x1ABC9C,
    "Wildfire": 0x27AE60,
    "HazMat": 0xF1C40F,
    "Technical": 0x95A5A6,
    "Airport": 0x9B59B6,
}
_DEFAULT_COLOUR = 0x5865F2  # blurple, for missions without a mapped discipline


def _truncate(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


def _truncate_lines(lines: list[str], limit: int = 1024) -> str:
    """Join lines within an embed-field budget, noting how many were cut."""
    out: list[str] = []
    used = 0
    for index, line in enumerate(lines):
        extra = len(line) + (1 if out else 0)
        remaining = len(lines) - index
        suffix = f"\n… and {remaining} more"
        if used + extra + len(suffix) > limit:
            out.append(f"… and {remaining} more")
            break
        out.append(line)
        used += extra
    return "\n".join(out)


def thread_title(name: str, key: str) -> str:
    """``"{name} · #{key}"`` within Discord's 100-char thread-name limit —
    the key suffix is only truncated (sacrificing the recovery marker) in
    the pathological case where the key alone exceeds the limit."""
    suffix = f" · #{key}"
    room = max(1, 100 - len(suffix))
    return _truncate(f"{_truncate(name, room)}{suffix}", 100)


def thread_key(title: str) -> str | None:
    """Parse the mission key back out of a thread title (adopt/recovery)."""
    match = _TITLE_KEY_RE.search(title or "")
    return match.group(1) if match else None


def build_mission_embed(
    mission: dict, *, base_url: str, updated: str | None = None
) -> discord.Embed:
    """The full mission card. Empty sections are omitted; long lists are
    trimmed per field, and the whole embed is re-trimmed if it would blow
    Discord's 6000-character total."""
    key = catalog.mission_key(mission)
    name = catalog.mission_name(mission)
    colour = _DISCIPLINE_COLOURS.get(
        catalog.discipline_of(mission) or "", _DEFAULT_COLOUR
    )

    credits = mission.get("average_credits")
    try:
        credits_text = f"{int(credits):,} average"
    except (TypeError, ValueError):
        credits_text = str(credits) if credits else "Unknown"

    categories = mission.get("mission_categories") or []
    type_text = (
        ", ".join(catalog.format_field_name(str(c)) for c in categories) or "—"
    )

    vehicles, trainings = catalog.requirement_lines(mission)
    unlocks = catalog.unlock_lines(mission)

    fields: list[tuple[str, str, bool]] = [
        ("💰 Credits", credits_text, True),
        ("🏢 Generated by", catalog.generated_by(mission), True),
        ("📂 Type", _truncate(type_text, 1024), True),
    ]
    if vehicles:
        fields.append(("🚒 Vehicles & equipment", _truncate_lines(vehicles), False))
    if trainings:
        fields.append(("🎓 Trainings", _truncate_lines(trainings), False))
    if unlocks:
        fields.append(("🔓 Unlock requirements", _truncate_lines(unlocks), False))
    patients = catalog.patient_summary(mission)
    if patients:
        fields.append(("🧑‍⚕️ Patients", _truncate(patients, 1024), False))
    prisoners = catalog.prisoner_summary(mission)
    if prisoners:
        fields.append(("🚔 Prisoners", prisoners, False))
    towing = catalog.towing_summary(mission)
    if towing:
        fields.append(("🧲 Towing", towing, False))
    pois = catalog.poi_list(mission)
    if pois:
        fields.append(("📍 POI", _truncate(", ".join(pois), 1024), False))
    expansions = catalog.expansion_names(mission)
    if expansions:
        fields.append(("🔁 Expands to", _truncate(", ".join(expansions), 1024), False))

    stamp = updated or dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")
    footer = f"Mission #{key} · source: einsaetze.json · updated {stamp}"

    # Fit the 6000-char embed total by tightening field budgets if needed.
    for field_limit in (1024, 512, 256):
        embed = discord.Embed(
            title=_truncate(name, 256),
            url=catalog.detail_url(mission, base_url),
            colour=discord.Colour(colour),
        )
        for field_name, value, inline in fields:
            embed.add_field(
                name=field_name, value=_truncate(value, field_limit), inline=inline
            )
        embed.set_footer(text=footer)
        if len(embed) <= 5900:
            break
    return embed


class MissionsForumService:
    """Syncs the mission catalog into the configured Discord forum."""

    # Pacing between Discord writes on top of the library's 429 handling.
    post_delay = 2.0
    batch_size = 10
    batch_delay = 10.0

    def __init__(
        self, cfg: Config, mc: MissionChiefClient, db: Database, bot
    ) -> None:
        self._cfg = cfg
        self._mc = mc
        self._bot = bot
        self._repo = MissionsForumRepo(db)
        self._state = StateRepo(db)
        # `!fra missionsforum stop` raises this; the running sync/wipe
        # loop checks it between posts and bows out cleanly.
        self._stop = False

    def request_stop(self) -> None:
        self._stop = True

    # ------------------------------------------------------------------
    # Channel plumbing
    # ------------------------------------------------------------------

    def forum(self) -> discord.ForumChannel | None:
        channel_id = self._cfg.discord.channels.missions_forum
        if not channel_id:
            return None
        channel = self._bot.get_channel(channel_id)
        if channel is None or not hasattr(channel, "create_thread"):
            return None
        return channel

    async def _get_thread(self, thread_id: int):
        """A thread by id, archived ones included; None when it's gone."""
        thread = self._bot.get_channel(thread_id)
        if thread is not None:
            return thread
        try:
            return await self._bot.fetch_channel(thread_id)
        except discord.NotFound:
            return None
        except discord.HTTPException as exc:
            log.warning("Could not fetch mission thread %s: %s", thread_id, exc)
            return None

    # ------------------------------------------------------------------
    # Tags
    # ------------------------------------------------------------------

    async def ensure_tags(self, forum) -> tuple[list[str], object]:
        """Create any missing forum tags (one bulk edit) and make sure
        posts require a tag. Returns (created tag names, fresh forum).

        The require_tag flag goes in a SEPARATE edit after the tags exist:
        Discord validates the flag against the forum's pre-edit tag list,
        so combining it with the tag creation fails on a fresh forum with
        40066 ("no tags available that can be set by non-moderators")."""
        def norm(name) -> str:
            return " ".join(str(name).split()).casefold()

        current = list(forum.available_tags)
        names = {norm(tag.name) for tag in current}
        # Renamed tags keep their id: the rename happens in place, so posts
        # already carrying the old tag follow along automatically. Matching
        # is case/whitespace-tolerant, and when BOTH names exist somehow,
        # the stale old tag is dropped instead of lingering forever.
        renamed = []
        for old, new in catalog.RENAMED_TAGS.items():
            old_n, new_n = norm(old), norm(new)
            if old_n not in names:
                continue
            if new_n in names:
                current = [t for t in current if norm(t.name) != old_n]
                names.discard(old_n)
                renamed.append(f"removed stale tag '{old}'")
                continue
            for tag in current:
                if norm(tag.name) == old_n:
                    tag.name = new
                    renamed.append(f"{old} → {new}")
                    names = (names - {old_n}) | {new_n}
                    break
        missing = [
            name for name in catalog.FORUM_TAG_EMOJI if norm(name) not in names
        ]
        # The fallback tag has priority: it is what keeps a tag-less
        # mission postable once require_tag is on.
        missing.sort(key=lambda name: name != catalog.FALLBACK_TAG)
        # Discord allows 20 tags per forum; never push it over.
        room = max(0, 20 - len(current))
        if len(missing) > room:
            log.warning(
                "Forum has only %d free tag slots; skipping tags: %s",
                room, ", ".join(missing[room:]),
            )
            missing = missing[:room]
        if missing or renamed:
            try:
                updated = await forum.edit(
                    available_tags=current + [
                        discord.ForumTag(name=name, emoji=catalog.FORUM_TAG_EMOJI[name])
                        for name in missing
                    ],
                    reason="Missions database tags",
                )
                forum = updated or forum
                for line in renamed:
                    log.info("Missions-forum tag renamed: %s", line)
            except discord.HTTPException as exc:
                # No Manage Channels on the forum? Keep posting (untagged
                # posts are allowed while require_tag is off) instead of
                # silently zero-progressing every day.
                log.warning("Could not create missions-forum tags: %s", exc)
                return [], forum
        # require_tag is a nice-to-have; only turn it on when the fallback
        # tag exists (otherwise a tag-less mission could never be posted),
        # and never let a refusal block the sync.
        names = {tag.name for tag in forum.available_tags}
        require_tag = bool(getattr(getattr(forum, "flags", None), "require_tag", False))
        if catalog.FALLBACK_TAG in names and not require_tag:
            try:
                updated = await forum.edit(require_tag=True)
                forum = updated or forum
            except discord.HTTPException as exc:
                log.warning(
                    "Could not enable require_tag on the missions forum: %s", exc
                )
        return missing + renamed, forum

    def _applied_tags(self, forum, mission: dict) -> list:
        by_name = {tag.name: tag for tag in forum.available_tags}
        wanted = catalog.derive_tags(mission)
        tags = [by_name[name] for name in wanted if name in by_name][:5]
        if not tags and catalog.FALLBACK_TAG in by_name:
            # require_tag forums refuse tag-less posts.
            tags = [by_name[catalog.FALLBACK_TAG]]
        return tags

    # ------------------------------------------------------------------
    # Adopt (DB-loss recovery)
    # ------------------------------------------------------------------

    async def adopt(self, forum) -> int:
        """Rebuild the mission→thread mapping from thread titles, so an
        empty database never causes a duplicate flood. Adopted rows get an
        empty content hash — the next sync refreshes their content."""
        adopted = 0
        threads = list(getattr(forum, "threads", []) or [])
        try:
            async for thread in forum.archived_threads(limit=None):
                threads.append(thread)
        except discord.HTTPException as exc:
            log.warning("Could not list archived mission threads: %s", exc)
        for thread in threads:
            key = thread_key(getattr(thread, "name", ""))
            if not key or await self._repo.get(key) is not None:
                continue
            await self._repo.record(key, thread.id, "", getattr(thread, "name", ""))
            adopted += 1
        return adopted

    # ------------------------------------------------------------------
    # Sync
    # ------------------------------------------------------------------

    async def sync(self, *, limit: int | None = None, force: bool = False) -> dict:
        """One full pass: fetch the catalog, ensure tags, post new missions,
        edit changed ones. Returns a summary dict with ``lines`` for humans.

        ``limit`` caps posts+edits this run (default: config
        ``max_posts_per_run``); ``force`` re-renders even unchanged posts.
        """
        self._stop = False
        forum = self.forum()
        if forum is None:
            return self._summary(
                error="Missions forum is not configured — set a forum channel "
                      "id with `!fra set missions_forum <id>`."
            )

        try:
            missions = await catalog.fetch_catalog(self._mc)
        except ValueError as exc:
            return self._summary(error=f"einsaetze.json is unusable: {exc}")
        if not missions:
            return self._summary(error="einsaetze.json returned no missions.")

        tags_created, forum = await self.ensure_tags(forum)

        # Empty mapping + existing posts = the DB was lost; re-adopt instead
        # of reposting 450 duplicates.
        adopted = 0
        if await self._repo.count() == 0:
            adopted = await self.adopt(forum)

        # Announce only once the whole catalog has been posted at least
        # once — no run of the (multi-run) initial backfill may ping.
        backfill_done = await self._state.get(STATE_BACKFILL_DONE) is not None
        announce = (
            self._cfg.automation.missions_forum.announce_new and backfill_done
        )

        # Untracked threads with our title marker (a crash between post and
        # bookkeeping, or a partial adopt) — reclaim instead of duplicating.
        orphans: dict[str, object] = {}
        for thread in getattr(forum, "threads", []) or []:
            orphan_key = thread_key(getattr(thread, "name", ""))
            if orphan_key:
                orphans[orphan_key] = thread

        cap = limit or self._cfg.automation.missions_forum.max_posts_per_run
        base_url = self._cfg.missionchief.base_url
        updated_stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")

        created = updated = skipped = failed = announced = 0
        capped = stopped = False
        seen_unchanged: list[str] = []
        seen_keys: set[str] = set()
        writes = 0

        missions.sort(key=lambda m: _sort_key(catalog.mission_key(m)))
        for mission in missions:
            if self._stop:
                stopped = True
                break
            key = catalog.mission_key(mission)
            if key in seen_keys:
                log.warning("Duplicate mission key %s in einsaetze.json; skipped", key)
                continue
            seen_keys.add(key)
            digest = catalog.content_hash(mission)
            row = await self._repo.get(key)
            if row is None and key in orphans:
                # Reclaim the existing thread; the empty hash forces a
                # content refresh below.
                orphan = orphans[key]
                await self._repo.record(
                    key, orphan.id, "", catalog.mission_name(mission)
                )
                row = await self._repo.get(key)
            if row is not None and row["content_hash"] == digest and not force:
                seen_unchanged.append(key)
                skipped += 1
                continue
            if writes >= cap:
                capped = True
                break
            try:
                if row is None:
                    thread = await self._create_post(
                        forum, mission, digest, updated_stamp, base_url
                    )
                    created += 1
                    if announce and thread is not None:
                        announced += await self._announce(mission, thread)
                else:
                    outcome = await self._update_post(
                        forum, mission, row, digest, updated_stamp, base_url
                    )
                    if outcome == "recreated":
                        created += 1
                    else:
                        updated += 1
            except discord.HTTPException as exc:
                failed += 1
                log.error("Mission forum post %s failed: %s", key, exc)
                continue
            writes += 1
            await self._pause(writes)

        await self._repo.touch_seen(seen_unchanged)
        if not capped and not failed and not stopped:
            # Whole catalog covered in one run: the backfill is done and
            # future creations are genuinely new missions.
            await self._state.set(STATE_BACKFILL_DONE, updated_stamp)
        summary = self._summary(
            created=created, updated=updated, skipped=skipped, failed=failed,
            announced=announced, adopted=adopted, tags_created=tags_created,
            capped=capped, cap=cap, total=len(missions), stopped=stopped,
        )
        await self._state.set(
            STATE_LAST_SYNC,
            dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
            + " — " + summary["lines"][0],
        )
        return summary

    async def _create_post(
        self, forum, mission: dict, digest: str, stamp: str, base_url: str
    ):
        key = catalog.mission_key(mission)
        name = catalog.mission_name(mission)
        embed = build_mission_embed(mission, base_url=base_url, updated=stamp)
        result = await forum.create_thread(
            name=thread_title(name, key),
            embed=embed,
            applied_tags=self._applied_tags(forum, mission),
            reason="Missions database sync",
        )
        thread = getattr(result, "thread", result)
        await self._repo.record(key, thread.id, digest, name)
        return thread

    async def _update_post(
        self, forum, mission: dict, row, digest: str, stamp: str, base_url: str
    ) -> str:
        """Edit an existing post in place; repost if its thread is gone."""
        key = catalog.mission_key(mission)
        name = catalog.mission_name(mission)
        thread = await self._get_thread(int(row["thread_id"]))
        if thread is None:
            # The thread was deleted by hand — post it again.
            await self._repo.delete(key)
            await self._create_post(forum, mission, digest, stamp, base_url)
            return "recreated"
        if getattr(thread, "archived", False):
            await thread.edit(archived=False)
        embed = build_mission_embed(mission, base_url=base_url, updated=stamp)
        try:
            starter = await thread.fetch_message(thread.id)
        except discord.NotFound:
            # The starter message was deleted but the thread remains: the
            # post can't be repaired in place, so replace it — otherwise
            # this mission would fail on every sync forever.
            log.warning(
                "Starter message of mission %s (thread %s) is gone; reposting",
                key, thread.id,
            )
            await self._repo.delete(key)
            await self._create_post(forum, mission, digest, stamp, base_url)
            return "recreated"
        await starter.edit(embed=embed)
        title = thread_title(name, key)
        wanted_tags = self._applied_tags(forum, mission)
        current_tags = {
            getattr(t, "name", None) for t in getattr(thread, "applied_tags", [])
        }
        edits: dict = {}
        if getattr(thread, "name", None) != title:
            edits["name"] = title
        if {t.name for t in wanted_tags} != current_tags:
            edits["applied_tags"] = wanted_tags
        if edits:
            await thread.edit(**edits)
        await self._repo.record(key, thread.id, digest, name)
        return "updated"

    async def wipe(self) -> dict:
        """Delete EVERY mission post (tracked rows plus any thread carrying
        our title marker) and forget the mapping — a clean slate for a full
        repost. The backfill flag resets too, so the repost never floods the
        announcement channel."""
        self._stop = False
        forum = self.forum()
        if forum is None:
            return self._summary(
                error="Missions forum is not configured — nothing to wipe."
            )
        # Tracked posts first, then marker-titled strays (adopt-style scan).
        targets: dict[int, str | None] = {}
        for row in await self._repo.all():
            targets[int(row["thread_id"])] = row["mission_key"]
        threads = list(getattr(forum, "threads", []) or [])
        try:
            async for thread in forum.archived_threads(limit=None):
                threads.append(thread)
        except discord.HTTPException as exc:
            log.warning("Could not list archived mission threads: %s", exc)
        for thread in threads:
            if thread_key(getattr(thread, "name", "")):
                targets.setdefault(thread.id, None)

        deleted = failed = 0
        stopped = False
        for thread_id, mission_key in targets.items():
            if self._stop:
                stopped = True
                break
            thread = await self._get_thread(thread_id)
            if thread is None:
                if mission_key:
                    await self._repo.delete(mission_key)
                continue
            try:
                await thread.delete()
            except discord.HTTPException as exc:
                failed += 1
                log.error("Could not delete mission thread %s: %s", thread_id, exc)
                continue
            if mission_key:
                await self._repo.delete(mission_key)
            deleted += 1
            await self._pause(deleted)

        await self._state.delete(STATE_BACKFILL_DONE)
        lines = [f"deleted {deleted} post(s), {failed} failed"]
        if stopped:
            lines.append("⏹️ stopped by admin — run wipe again for the rest")
        remaining = await self._repo.count()
        if remaining:
            lines.append(f"{remaining} mapping row(s) left (their threads remain)")
        return {
            "error": None, "deleted": deleted, "failed": failed,
            "stopped": stopped, "lines": lines, "changed": bool(deleted or failed),
        }

    async def _announce(self, mission: dict, thread) -> int:
        channel_id = self._cfg.discord.channels.mission_announce
        channel = self._bot.get_channel(channel_id) if channel_id else None
        if channel is None:
            return 0
        name = catalog.mission_name(mission)
        jump = getattr(thread, "jump_url", "") or getattr(thread, "mention", "")
        try:
            await channel.send(
                f"🆕 **New mission in MissionChief:** {name}\n➡️ {jump}"
            )
            return 1
        except discord.HTTPException as exc:
            log.warning("Could not announce new mission %s: %s", name, exc)
            return 0

    async def _pause(self, writes: int) -> None:
        if self.post_delay:
            await asyncio.sleep(self.post_delay)
        if self.batch_delay and writes % self.batch_size == 0:
            await asyncio.sleep(self.batch_delay)

    # ------------------------------------------------------------------
    # Status
    # ------------------------------------------------------------------

    async def status_lines(self) -> list[str]:
        auto = self._cfg.automation.missions_forum
        channels = self._cfg.discord.channels
        forum = self.forum()
        lines = [
            "forum: "
            + (
                f"<#{channels.missions_forum}>"
                + ("" if forum else " (⚠️ not reachable / not a forum)")
                if channels.missions_forum else "not set (`!fra set missions_forum <id>`)"
            ),
            f"tracked posts: {await self._repo.count()}",
            f"daily sync: {'on, ' + auto.sync_time if auto.enabled else 'OFF'}"
            f" · post cap {auto.max_posts_per_run}/run",
            "new-mission ping: "
            + (
                f"on → <#{channels.mission_announce}>"
                if auto.announce_new else "off"
            ),
        ]
        last = await self._state.get(STATE_LAST_SYNC)
        lines.append(f"last sync: {last or 'never'}")
        return lines

    @staticmethod
    def _summary(*, error: str | None = None, **counts) -> dict:
        if error:
            return {"error": error, "lines": [error], "changed": False}
        created = counts.get("created", 0)
        updated = counts.get("updated", 0)
        lines = [
            f"created {created}, updated {updated}, "
            f"unchanged {counts.get('skipped', 0)}, failed {counts.get('failed', 0)} "
            f"(of {counts.get('total', 0)} missions)"
        ]
        if counts.get("tags_created"):
            lines.append("tag changes: " + ", ".join(counts["tags_created"]))
        if counts.get("adopted"):
            lines.append(
                f"re-adopted {counts['adopted']} existing post(s) from the forum"
            )
        if counts.get("announced"):
            lines.append(f"announced {counts['announced']} new mission(s)")
        if counts.get("stopped"):
            lines.append("⏹️ stopped by admin — the rest follows on the next sync")
        elif counts.get("capped"):
            lines.append(
                f"post cap reached ({counts.get('cap')}/run) — "
                "the rest follows on the next sync"
            )
        changed = bool(
            created or updated or counts.get("failed", 0)
            or counts.get("tags_created") or counts.get("adopted")
        )
        return {**counts, "error": None, "lines": lines, "changed": changed}


def _sort_key(key: str) -> tuple:
    """Numeric-aware ordering so mission 2 posts before mission 10."""
    head = re.match(r"(\d+)", key)
    return (int(head.group(1)) if head else 10**9, key)
